
class AuthException(Exception):
    pass


class UserExistsError(Exception):
    pass
